language: node_js
node_js: stable

script: npm run build

before_deploy:
  - ls
  - rm .gitignore
  - echo 'node_modules' > .gitignore
  - git add .

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
